use_frameworks!

platform :ios, '10.0'

target 'methinksAppTest_Example' do
  pod "methinksAppTest"

  target 'methinksAppTest_Tests' do
    inherit! :search_paths

    
  end
end

target 'methinksAppTest_LITE-Example' do
  pod "methinksAppTest_LITE"
end
